export const environment = {
  production: true,
  apiUrl: 'https://anapioficeandfire.com/api',
  booksPath: 'books',
  serverApiUrl: 'http://localhost:8080',
  favoritesPath: 'api/favorites',
  authPath: 'api/auth',
  register: 'register',
  me: 'me',
  logout: 'logout',
  login: 'login',
  coverLibraryApiUrl: 'https://covers.openlibrary.org/b/isbn',
  imageFailFormat: 'jpg',
  wikipediaApiUrl: 'https://en.wikipedia.org/api/rest_v1/page/summary',
  charactersPath: 'characters',
} as const;
